name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Сценарий запускается только при пуше в ветку main

permissions:
  contents: write # Разрешаем запись, чтобы скрипт мог обновлять файлы

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # Быстрая и чистая установка пакетов для CI/CD

      - name: Build project
        run: npm run build # Vite собирает проект в папку dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Сервер берет готовую сборку из dist
          branch: gh-pages # И автоматически обновляет ветку gh-pages
